    format = "<span foreground='#00ff80'><b>%s</b></span>\n<span foreground='#80ffcc'>%b</span>"

[urgency_low]
    background = "#0a0e17"
    foreground = "#5ea488"
    frame_color = "#0d3326"
    highlight = "#00ff80"
    timeout = 4

[urgency_normal]
    background = "#0a0e17"
    foreground = "#80ffcc"
    frame_color = "#00ff8038"
    highlight = "#00ff80"
    timeout = 7

[urgency_critical]
    background = "#0a0e17"
    foreground = "#b3ffdd"
    frame_color = "#ff453a80"
    highlight = "#ff453a"
    timeout = 0
