background            #1a1a1a
foreground            #ffffff
selection_background  #0055ff
selection_foreground  #ffffff
url_color             #33aaff
cursor                #ffffff
cursor_text_color     #1a1a1a
active_tab_background   #0033aa
active_tab_foreground   #ffffff
inactive_tab_background #2a2a2a
inactive_tab_foreground #bbbbbb
color0  #000000
color1  #ff0000
color2  #33ff33
color3  #ffff00
color4  #3399ff
color5  #cc33cc
color6  #00ffff
color7  #d0d0d0
color8  #808080
color9  #ff5555
color10 #55ff55
color11 #ffff55
color12 #66aaff
color13 #ff66ff
color14 #66ffff
color15 #ffffff

