background {
    monitor =
    path = /home/nuus/code/backgrounds/beautiful-pngs/7.png
    blur_size = 4
    blur_passes = 2
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    fade_on_empty = true
}

label {
    monitor =
    text = $USER
    color = rgba(255, 255, 255, 1.0)
    font_size = 20
    position = 0, 100
    halign = center
}

