general {
    lock_cmd = pgrep -x hyprlock || hyprlock
    unlock_cmd = notify-send "unlock!"     
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = notify-send "Awake!"
    ignore_dbus_inhibit = false          
    ignore_systemd_inhibit = false      
    inhibit_sleep = 3
}

listener {
    timeout = 900 # in seconds -- (15 minutes)
    on-timeout = hyprlock
    on-resume = notify-send "Welcome back!"
}
