background_opacity 0.96

background #ffffff
foreground #14251f
cursor #006b46
cursor_text_color #ffffff
selection_background #006b46
selection_foreground #ffffff
url_color #006477
url_style single

color0 #14251f
color1 #a92d32
color2 #006b46
color3 #725500
color4 #005d80
color5 #643589
color6 #006477
color7 #405b50

color8 #536a60
color9 #a92d32
color10 #006b46
color11 #725500
color12 #005d80
color13 #643589
color14 #006477
color15 #14251f

active_tab_background #006b46
active_tab_foreground #ffffff
inactive_tab_background #e5ece8
inactive_tab_foreground #405b50
